### PR TITLE
Remove dependency to vault root package

### PR DESCRIPTION
**Pull request by jawher**
lib-vault depends on `github.com/hashicorp/vault` for test purproses.

However, according the vault maintiners (https://github.com/hashicorp/vault/issues/9575#issuecomment-665013482)

> No one should be importing github.com/hashicorp/vault, only the api and sdk modules. The top-level vault module is not intended to be a dependency for other projects, we're using go.mod solely to manage our own dependencies here.

Also, the current referenced vault version has critical CVEs, and we are unable to upgrade it:

Some failed trials:

```
❯ go get -u github.com/hashicorp/vault
go get: github.com/hashicorp/vault@v1.9.0 requires
	github.com/hashicorp/vault/api/auth/approle@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

```
go get  github.com/hashicorp/vault@v1.8.5
go: downloading github.com/hashicorp/go-secure-stdlib/base62 v0.1.1
go: downloading github.com/hashicorp/go-secure-stdlib/password v0.1.1
go: downloading github.com/evanphx/json-patch/v5 v5.5.0
go: downloading github.com/hashicorp/go-secure-stdlib/tlsutil v0.1.1
github.com/hashicorp/vault imports
	github.com/hashicorp/vault/command imports
	github.com/hashicorp/vault/builtin/credential/aws imports
	github.com/hashicorp/vault/sdk/helper/awsutil: cannot find module providing package github.com/hashicorp/vault/sdk/helper/awsutil
```

### CODE REVIEW

**Review by tbeaugrand — APPROVED** [review]

**Comment by jawher** [comment]
@tbeaugrand tu sais si notre usage de vault à nous se fait en KV V1 ou V2 ? genre est ce que ça vaut le coup de remettre les tests de list/read/get secret en v1 avec docker ?

**Comment by tbeaugrand** [comment]
Notre Vault est uniquement en V1

**Comment by tbeaugrand** [comment]
@jawher on merge et on release ?

**Comment by jawher** [comment]
@tbeaugrand là dans l'état on n'a plus de tests avec le vault en kv v1 😢

**Comment by tbeaugrand** [comment]
@jawher tu penses quoi de #13

**Comment by jawher** [comment]
Superssed by #13

**Pull request closed without merging**
